### ISSUE TITLE
App does not display schema properties whose keys start with URL-encoding

### ISSUE THREAD

**Issue by ddohler** [WorldBank-Transport/DRIVER-Android#45]
A schema containing the property / definitions key `%D8%B4%D8%AE%D8%B5%2FPerson` did not show up correctly in the Android app -- the Person section was skipped. Manually changing the key to `person` solved the issue.

**Comment by flibbertigibbet** [comment]
Do we want or need to support arbitrary special characters and URL encoding for internal variable names?

Why was the doubled 'Arabic/English' format used in the schema property key (used internally) and not just for the label, which users see? I believe the latest fallback schema I loaded only used that 'Arabic/English' format for the labels used in display. Further, why is the property key URL encoded? I expect that to break URI field cross-referencing according to the JSON schema specification, which will expect the referent property name to be the decoded version. As long as we can display arbitrary text in the user-facing label, I don't think it worthwhile to support the same for internal model naming.

The property name must be translated into a valid variable name for use, so disallowed characters (such as the forward slash, and much of the URL encoding) will be substituted with underscores or dropped, with further processing to add extra characters to handle resultant name collisions if necessary, breaking idempotence of the process. The variable names in use must be things that can be reconstructed reliably for introspection. Arabic letters should be fine for Java, which accepts Unicode letters in variable names. It's special characters such as the forward slash that will cause issues. White space is already handled appropriately with camel-casing.

I think the issue is actually that the admin editor should not allow such special characters to be used for property key names nor URL encode keys for storage on the model. I'd be surprised if such a field name doesn't break anything else, like search or cross-field referencing in the web app.

If you agree, I'll go open an issue on the other repo to do some validation on the editor property key input.

**Comment by ddohler** [comment]
It turned out later that this is likely a red herring; I'm going to open another issue and close this one; the URI encoding doesn't seem to be causing issues anywhere else and it may not have caused this problem either. If URI encoding turns out to be a problem in fact, we can re-open this or open an issue on the schema editor, as appropriate.
